[project]
name = "py-x402"
version = "0.1.0"
description = "X402 Implementation for Popular Python Frameworks"
authors = [
    { name = "Dan Murphy" }
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "web3>=7.12.0",
]

[tool.uv]
